# Generated by Django 3.0.4 on 2020-03-29 02:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bibHome', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bib',
            old_name='date_posted',
            new_name='date_searched',
        ),
    ]
